api_platform:

    # The title of the API.
    title: 'Simple Billing API doc'

    # The description of the API.
    description: "Simple Billing Api DOC"

    # The version of the API.
    version: "0.0.0"

    # Specify a name converter to use.
    name_converter: ~

    # Specify a path name generator to use.
    path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'

    eager_loading:
        # To enable or disable eager loading.
        enabled: true

        # Fetch only partial data according to serialization groups.
        # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
        fetch_partial: false

        # Max number of joined relations before EagerLoading throws a RuntimeException.
        max_joins: 30

        # Force join on every relation.
        # If disabled, it will only join relations having the EAGER fetch mode.
        force_eager: true
    # Enable the FOSUserBundle integration.
    enable_fos_user: false

    # Enable the Nelmio Api doc integration.
    enable_nelmio_api_doc: true

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    # Enable the entrypoint.
    enable_entrypoint: true

    # Enable the docs.
    enable_docs: true

    oauth:
        # To enable or disable oauth.
        enabled: true

        # The oauth client id.
        clientId: 'NtTh6z54N8Jbv4RX'

        # The oauth client secret.
        clientSecret: 'nGZk83557PbRdPsF'

        # The oauth type.
        type: 'oauth2'

        # The oauth flow grant type.
        flow: 'password'

        # The oauth token url.
        tokenUrl: '/oauth/v2/token'

        # The oauth authentication url.
        authorizationUrl: '/oauth/v2/auth'

        # The oauth scopes.
        scopes: []

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
            json:     ['application/json']
            jsonld:   ['application/ld+json']
            jsonhal:  ['application/hal+json']
            xml:      ['application/xml', 'text/xml']
            html:     ['text/html']
            myformat: ['application/vnd.myformat']
